# **Otimização por Colônia de Formigas**
> A Otimização por Colônia de Formigas, *Ant Colony Optimization* - ACO, é uma técnica inspirada na busca por fonte de alimento realizada por colônias de formigas, a qual é aplicada a problemas discretos de otimização.

> A metáfora central da ACO reside no mecanismo de comunicação indireta através de sinais químicos (feromônios), empregado por muitas espécies de formigas sociais, na busca por fontes de alimentos. As formigas buscam aleatoriamente por fontes de alimento próximas aos seus ninhos, sendo que a “força” da trilha de feromônio cresce rapidamente para fontes próximas e para trilhas mais curtas. As trilhas surgem ao longo do tempo, como uma memória coletiva, formando uma rota entre a colônia e a fonte de alimento (Figura 1).

Figura 1. Depósito de feromônio entre o ninho (N) e a fonte de alimento (F)

<img src="https://drive.google.com/uc?id=1oCFZzpApf-ctuWxZ_ZiqmcinVMr3UvDC" width="500">

> O presente notebook colab, pretende introduzir à ACO. A codificação foi baseada na biblioteca ACO-Pants e nos exemplos disponíveis em {1}.
>* Abaixo podemos visualizar a importação dos pacotes e módulos necessários.
---
{1} ACO-Pants. A Python3 implementation of the Ant Colony Optimization Meta-Heuristic. Disponível em: https://pypi.org/project/ACO-Pants/. Acesso em: 5 abr 2021.

In [ ]:
#[1] Importando pacotes e módulos

!pip install ACO-Pants # Instalação de ACO-Pants

import pants
import math
import random
import numpy

  Preparing metadata (setup.py) ... done
  Created wheel for ACO-Pants: filename=ACO_Pants-0.5.2-py3-none-any.whl size=18840 sha256=602b1f3d8f47fdfa26592a904f5797341681512d88cab7a68a911d0975f0bc83
  Stored in directory: /root/.cache/pip/wheels/67/2d/eb/6b998bf9d6c81e3b2a840ffb9b8afb3d93a7568f6e14fa426f
Successfully built ACO-Pants


#**Seleção e Formulação do Problema**
> O primeiro passo para utilizar a ACO é mapear o problema selecionado para um grafo no qual a rota (trilha mais forte de feromônios) representa a solução do problema. A tarefa é encontrar um caminho ótimo através do grafo.

> Dessa forma, nada mais natural do que escolher o clássico **Problema do Caixeiro Viajante**. O **Problema do Caixeiro Viajante**, ou *Travelling Salesman Problem*, reside no objetivo de encontrar a menor rota possível para visitar um conjunto de cidades, passando por cada uma delas uma única vez, e retornar à origem.
* O espaço de estados para esse problema pode ser representado por um grafo completamente conexo. Os vértices são as cidades e as arestas representam vias entre cidades, havendo uma distância (custo) associada.
* O trecho de código abaixo gera um grafo para o problema do caixeiro viajante.
  * O usuário pode escolher o número de cidades;
  * O grafo é gerado em uma matriz bidimensional, sendo as distâncias valores inteiros aleatórios no intervalo [10, 100].


In [ ]:
#[2] Geração do grafo para o problema do caixeiro

# função graphTSP(numCities, minDist, maxDist)
# parâmetros:
#   numCities: número de cities
#   minDist: menor valor de distância
#   maxDist: maior valor de distância
# retorno:
#   cities: grafo de cidades (Matriz numCities X numCities). As distância
#   entre duas cidades são determinadas aleatoriamente entre minDist e maxDist
def graphTSP(numCities, minDist, maxDist):
  cities = numpy.zeros((numCities, numCities), dtype = int)
  for i in range(numCities):
    for j in range(numCities):
      if (j>i):
        cities[i, j] = random.randint(minDist, maxDist)
      elif (j<i):
        cities[i, j] = cities[j, i]
  return cities

numCities = 5     #  Número de cidade inicial

while(True):
  numCities = int(input('Digite o número de cidades: '))
  if (numCities > 4):
    break
  else:
    print('O número de cidades deve ser maior que 4!')

cities = graphTSP(numCities, 10, 100)

# Função dist(cid1, cid2):
# parâmetros:
#   cid1: cidade de origem (vértice de origem)
#   cid2: cidade de destino (vértice de destino)
# retorno:
#   dist = distância entre as cidades (custo da aresta)
def dist(cid1, cid2):
  return cities[cid1][cid2]

print('cidades:')
print(cities)

Digite o número de cidades: 10
cidades:
[[ 0 61 96 37 25 42 21 56 71 94]
 [61  0 68 52 30 84 46 37 57 70]
 [96 68  0 23 51 15 39 69 72 81]
 [37 52 23  0 28 77 98 62 32 27]
 [25 30 51 28  0 45 45 56 12 91]
 [42 84 15 77 45  0 41 40 72 23]
 [21 46 39 98 45 41  0 59 56 30]
 [56 37 69 62 56 40 59  0 21 90]
 [71 57 72 32 12 72 56 21  0 28]
 [94 70 81 27 91 23 30 90 28  0]]


#**Processamento da ACO**
> A Figura 2 apresenta o pseudocódigo simplifica do algoritmo da ACO. Em cada iteração do algoritmo o feromônio em cada aresta, além de atualizado com o depósito, sofre evaporação.

Figura 2. Pseudocódigo da ACO

<img src="https://drive.google.com/uc?id=1gjVPxanOnvi4Pyge86hZzlJCgzzqbMG9" width="700">

>No pacote ACO-Pants, esse processamento do algoritmo é transparente ao usuário.

In [ ]:
#[3] Representação do mundo e processamento do algoritmo
nodes = list(range(numCities))

# Cria a representação do mundo (world) a partir dos nós (nodes) e função de distância (dist)
world = pants.World(nodes, dist)

# Cria o Solver
solver = pants.Solver()

# Busca pela melhor solução (Processamento do Algoritmo)
solution = solver.solve(world)

print('Caminho:', solution.tour)    # Nós visitados
print('Custo Total:', solution.distance) # Custo do melhor caminho encontrado

Caminho: [6, 9, 5, 2, 3, 8, 7, 1, 4, 0]
Custo Total: 257
